- drivers/gpu/drm/i915_legacy/i915_reg.h
- drivers/gpu/drm/i915_legacy/intel_cdclk.c
- drivers/gpu/drm/i915_legacy/intel_workarounds.c
Upstream commits:
- https://github.com/gregkh/linux/commit/07c37f641842fb6676e925b4747702ad8e84ce94
- https://github.com/gregkh/linux/commit/c0e2dbd7d7070efc8540a1a44d4540d44fdbfd97
- https://github.com/gregkh/linux/commit/d05cba91e1ded34321cb0c9f7062e1621d524b91
- https://github.com/gregkh/linux/commit/abb4c8b10fc7cfba06acf3869345ebed7dc27088
- https://github.com/gregkh/linux/commit/a22fc7cea6afb8901210e23a08e1350a589f0f39
- https://github.com/gregkh/linux/commit/0b50b2beafe72117580ee1157d093138e2161774
- https://github.com/gregkh/linux/commit/051d85e1b2d32cdf5dd9b723c8b9dea220a43f3b
Any upstream commit can be applied to i915_legacy using this scriptlet:
```bash
$ COMMIT="https://github.com/gregkh/linux/commit/051d85e1b2d32cdf5dd9b723c8b9dea220a43f3b"
$ curl $COMMIT.patch | sed …
```
> Update i915_legacy to 5.2.15

- drivers/hid/hid-multitouch.c
- drivers/misc/ipts/ipts-dbgfs.c
- drivers/misc/ipts/ipts-mei.c
- drivers/misc/ipts/ipts-msg-handler.c
- drivers/misc/ipts/ipts-msg-handler.h
Previous discussion:
* https://github.com/jakeday/linux-surface/issues/549
Currently, IPTS exposes two seperate touchscreen devices: One for single-touch and one for multi-touch. However, this confuses window managers such as GNOME's mutter, who cannot know which one is active at the moment. The result of that is that mutter will always rotate the single-touch device. The multi-touch one isn't rotated properly, even though multi-touch mode is whats probably being used in most cases. I am not sure if anyone actually uses single-touch mode to be honest.
Since the original IPTS implementation modified hid-multitouch to make single-touch mode work [1], reverting those changes disables single-touch, and fixes the touch input rotation in mutter. (Courtesy of @kitakar5525). This has the …
> Fix touch input rotation / Disable single-touch mode

- .gitignore
- arch/x86/Makefile
- scripts/sign_kernel.sh
This adds the ability for you and other packagers to pre-sign the kernels for secureboot. 
The kernel build system will look for two files:
* `keys/MOK.key` (private key)
* `keys/MOK.crt` (public key in PEM format)
and sign the produced vmlinux / bzImage file with it. If no keys are found, it will be silently ignored and the kernel will be unsigned.
Adding it to the build system avoids having to wrap everything. Right now you need to first to `make all`, then sign the image, and then do something like `make bindeb-pkg`. With this, you can just add your keys to the kernel source, and run `make deb-pkg`.
Users then only need to be able to download the public key (in DER format), and enroll it into `shim` to be able to boot the kernel - instead of generating the keys and signing the kernel …
> Add secureboot pre-signing to the kernel

- drivers/misc/ipts/companion/ipts-surface.c
Declaring the required firmware files as MODULE_FIRMWARE makes it possible to include the driver in the initramfs, in case that is needed or desired.
Even though there are files that are loaded through a config file, that config file is the same for every Surface using IPTS, so this should be fine. (This might also change later in case we decide to remove the config file and move it's functions into the companion driver)
> Add firmware declarations for ipts_surface

- Documentation/driver-api/driver-model/devres.rst
- arch/sparc/include/asm/io_64.h
- drivers/mfd/intel-lpss.c
- include/linux/io.h
- lib/devres.c
Fix for #12, taken from LKML.
Upstream LKML: https://lkml.org/lkml/2019/10/16/1230
Upstream bugzilla: https://bugzilla.kernel.org/show_bug.cgi?id=203485
> Fix: Kernel panic at boot due to incorrect BAR specification for intel-lpss-pci

- drivers/misc/ipts/companion.c
- drivers/misc/ipts/companion.h
- drivers/misc/ipts/companion/ipts-surface.c
- drivers/misc/ipts/hid.c
- include/linux/ipts-companion.h
- include/linux/ipts.h
Having a DMI match for some surface devices doesn't really match with the concept of having a device-specific companion driver, so this moves the matching code to the companion.
ipts-surface is now setup in a way that allows us to add device-specificn data pretty easily. All you need is the interface to IPTS, which can just be copied from no_feedback.
> Move no_feedback DMI check to the companion driver

- drivers/misc/ipts/ipts.h
- drivers/misc/ipts/msg-handler.c
We don't want IPTS to set itself to singletouch mode in case it thinks that might fix anything, because it doesn't. Even a malfunctioning multitouch IPTS has a higher chance of working than singletouch.
This could potentially fix some of the stability issues that some models have. Even if not, it is one bit of confusing code less.
Note: I haven't had the time to test this yet, I just ran across it while working on something else. But it shouldn't cause any issues.
> ipts: Dont automatically switch sensor modes

- drivers/input/touchscreen/surface3_spi.c
Hello, on Surface 3, we're facing touch input crash with some kernel config setup, especially with your build and Arch Linux stock kernel.
It turned out that DMA mode seems to be broken with surface3-spi touchscreen driver. So, this commit will disable DMA mode by default and use PIO mode instead for the driver.
Any other changes beyond Surface 3 touchscreen are not intended.
If you find something is weird, let me know. Also, this is just a workaround, I should actually fix   this driver with DMA mode if I can. So, If you know how to set up DMA mode, also please let me know.
Link to issue: jakeday/linux-surface#596
Tested on Arch Linux 5.4.1 with Surface 3, which will use DMA by default.
This commit made the driver use PIO by default and no touch input crash.
Also tested on chromeos-4.19 …
> surface3-spi: workaround: disable DMA mode to avoid crash by default

- drivers/platform/x86/surface3-wmi.c
- sound/soc/codecs/rt5645.c
- sound/soc/intel/common/soc-acpi-intel-cht-match.c
As a request from a person who is also suffering from "OEMB" issue on IRC channel.
Please port this into also 4.19 and 5.4 kernels when approved this PR, should apply with no conflicts.
The first patch (ASoC) is from Android-x86 project. The second patch is made by me referring to the first patch (they don't have a similar patch for surface3-wmi, so I made it).
I credited the first patch author in commit message.
Fixes broken Sound and surface3-wmi driver probe on the affected systems.
---
On some Surface 3, DMI table gets corrupted for unknown reasons
and breaks existing DMI matching used for device-specific quirks.
This PR adds the (broken) DMI info for the affected systems.
On the affected systems, dmidecode will look like this:
```
$ sudo dmidecode
[...]
BIOS Information
Vendor: …
```
> Surface3-OEMB: add quirk for Surface 3 with broken DMI table

- arch/sparc/include/asm/io_64.h
- drivers/hid/hid-core.c
Revert the following two commits that are already upstreamed:
- "HID: Improve Windows Precision Touchpad detection."
- "sparc64: implement ioremap_uc"
Should apply with or without the PR:
- "[WIP] Backporting 5.3/5.4 changes into 4.19" #32
> v4.19: Revert upstreamed commits

- drivers/gpu/drm/i915/intel_guc_submission.c
After backporting 5.3/5.4 changes, checkpatch added one error compared
to IPTS patch for 5.3:
ERROR: else should follow close brace '}'
#386: FILE: drivers/gpu/drm/i915/intel_guc_submission.c:117:
+	}
+	else {
This commit fixes the error.
The cause of the new error is that when this error was fixed in a
later kernel, the change was not backported to 4.19. On 5.3, the
error was already fixed when IPTS support (871f089) was added.
> v4.19: ipts: Cleanup intel_guc_submission to pass checkpatch

- drivers/net/wireless/marvell/mwifiex/cfg80211.c
- drivers/net/wireless/marvell/mwifiex/sta_cmd.c
(This PR should also apply cleanly on 4.19 and 5.4)
It's known that ps_mode (power_save) causes connection instability. The change https://github.com/linux-surface/kernel/commit/264427bb5816c913a1abab9de59639eec299d972#diff-b645af90396992a038c24ef0d70bd262 reverted lines that forcibly overrides ps_mode to false.
And according to some reports, it seems that disabling ps_mode via config file is not so reliable.
So, this PR change back the ps_mode to disabled by default. Also, there may be no reason to keep it enabled by default if it's broken.
- What do you think, everyone? Should we really modify the driver to disable ps_mode by default by kernel side again?
---
I first tried to stop enabling ps_mode on initialization ("mwifiex: sta_cmd: do not enable ps_mode by default"). But …
> v5.5: mwifiex: disable ps_mode by default

- drivers/hid/hid-core.c
Fixes #37
---
This reverts commit 44c036ba808e1df71a4262999399a160bdd0d519.
Reason for revert:
Following upstream fixes incoming
- fa616c09626198ecea736fff251b72f8116c19f4
(HID: core: increase HID report buffer size to 8KiB)
- 75c3955b160d32a7faac6db094960c35723eebd4
(HID: core: fix off-by-one memset in hid_report_raw_event())
> v4.19: Revert "HID: Do not abort on over-sized reports"

- drivers/misc/ipts/hid.c
When building module with commit 589ab3dbf4af3412daa40524024e58f8b548d263, compiler gave me a warning.
---
Compiler outputs the following warning on build:
CC [M]  drivers/misc/ipts/hid.o
In file included from ./include/linux/input.h:22,
from ./include/linux/hid.h:36,
from drivers/misc/ipts/hid.c:11:
drivers/misc/ipts/hid.c: In function ‘ipts_handle_hid_data’:
drivers/misc/ipts/hid.c:307:19: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 3 has type ‘u32’ {aka ‘unsigned int’} [-Wformat=]
307 |    ipts_err(ipts, "input report too large (%lu bytes), skipping",
|                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./include/linux/device.h:1362:22: note: in definition of macro ‘dev_fmt’
1362 | #define dev_fmt(fmt) fmt
|                      ^~~ …
> Fixup: ipts: Do not forward report on overflow

- drivers/misc/ipts/companion.c
- drivers/misc/ipts/companion.h
- drivers/misc/ipts/companion/ipts-surface.c
- drivers/misc/ipts/hid.c
- drivers/misc/ipts/msg-handler.c
- drivers/misc/ipts/params.c
- drivers/misc/ipts/params.h
- include/linux/ipts-companion.h
- include/linux/ipts.h
@kitakar5525 and I figured out that the feedback sending I implemented for the new IPTS driver doesn't appear to cause the crashes on gen4 devices that lead to no_feedback being implemented. I backported it to this driver, and it works here as well: No crashes on a device that required no_feedback before.
The difference between the old implementation and this one is, that the old one got the feedback data that it sent through the GuC. We have no idea what data is sent, and how the ME reacts to it. Because the GuC is not useable on the new driver, it will send a buffer that contains nothing but the transaction / buffer ID. 
This causes an "Invalid Parameters" error from the ME, but touch data continues to be written into the buffers (as opposed to not sending feedback at all). The "Invalid …
> Backport simplified feedback sending and remove no_feedback

- drivers/misc/ipts/companion/ipts-surface.c
According to acpidump, MSHW0103 that is currently commented as "Unknown"
is also used on some SP4 [1].
This commit improves the comment.
[1] https://github.com/linux-surface/acpidumps/blob/cbe3115807a595d9148f57757adc42e9875ca5b8/surface_pro_4/dsdt.dsl#L16669-L16682
> ipts: companion: improve comment for hardware id on SP4

- drivers/net/wireless/marvell/mwifiex/sta_cmd.c
(once this PR gets approved, I'll make the same change to v4.19 and v5.4 branches or let me know if you guys want to do it by yourself.)
The commit 541813622549 ("mwifiex: sta_cmd: do not enable ps_mode by
default") stopped enabling ps_mode by default by just removing the
relevant code. But it's better to leave a comment there.
This commit adds a comment where the related code existed.
Signed-off-by: Tsuchiya Yuto (kitakar5525) <kitakar@gmail.com>
> mwifiex: sta_cmd: add comment for not enabling ps_mode by default

- drivers/net/wireless/marvell/mwifiex/pcie.c
- drivers/net/wireless/marvell/mwifiex/sta_cmd.c
(The first revert commit does not apply cleanly on v4.19 branch. So, I'll make the same change to v5.4 and v4.19 branch once this PR gets approved. Or let me know if you guys want to do it by yourself.)
This PR
1) reverts the large commit 456cdc416f6e ("wireless/mwifiex: Fix S0ix / suspend")
2) split the commit into three small commits
So, no functional changes are intended. Just split the commit to describe what each part does.
There are small changes from the reverted commit.
1) added a description to the top of suspend()/resume() functions (starting with 'XXX:')
2) used `pci_upstream_bridge()` instead of `bus->self->` and placed `bridge_d3` thing to the top of probe()
3) removed description regarding auto_ds from the top of the function
4) not changing the location of `int ret;`; the …
> mwifiex: split large commit into three commits

- drivers/input/misc/soc_button_array.c
(patch for 4.19 branch)
There is a warning from compiler when building v4.19-surface kernel that
backported button patches from newer kernels.
drivers/input/misc/soc_button_array.c: In function ‘soc_button_probe’:
drivers/input/misc/soc_button_array.c:381:19: warning: passing argument 2 of ‘devm_kfree’ discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
381 |   devm_kfree(dev, button_info);
|                   ^~~~~~~~~~~
In file included from ./include/linux/input.h:22,
from drivers/input/misc/soc_button_array.c:14:
./include/linux/device.h:695:50: note: expected ‘void *’ but argument is of type ‘const struct soc_button_info *’
695 | extern void devm_kfree(struct device *dev, void *p);
|                                            ~~~~~~^
This warning happens …
> v4.19: Input: soc_button_array - fix Wdiscarded-qualifiers for kernels below 4.20

- drivers/net/wireless/marvell/mwifiex/main.h
- drivers/net/wireless/marvell/mwifiex/pcie.c
When a reset performed but even that reset failed for some reasons (e.g.
on Surface devices, fw reset requires another quirk), a hang happens on
cancel_work_sync().
kernel: mwifiex_pcie 0000:01:00.0: WLAN FW already running! Skip FW dnld
kernel: mwifiex_pcie 0000:01:00.0: WLAN FW is active
kernel: mwifiex_pcie 0000:01:00.0: mwifiex_cmd_timeout_func: Timeout cmd id = 0xfa, act = 0xa000
kernel: mwifiex_pcie 0000:01:00.0: num_data_h2c_failure = 0
kernel: mwifiex_pcie 0000:01:00.0: num_cmd_h2c_failure = 0
kernel: mwifiex_pcie 0000:01:00.0: is_cmd_timedout = 1
kernel: mwifiex_pcie 0000:01:00.0: num_tx_timeout = 0
kernel: mwifiex_pcie 0000:01:00.0: last_cmd_index = 2
kernel: mwifiex_pcie 0000:01:00.0: last_cmd_id: 16 00 a4 00 fa 00 a4 00 7f 00
kernel: mwifiex_pcie 0000:01:00.0: last_cmd_act: 00 …
> mwifiex: pcie: skip cancel_work_sync() on reset failure path

- drivers/net/wireless/marvell/mwifiex/main.h
- drivers/net/wireless/marvell/mwifiex/pcie.c
- drivers/net/wireless/marvell/mwifiex/pcie.h
Hi, this PR is a successor of the previous PR (https://github.com/linux-surface/kernel/pull/57).
This PR
1. reverts previous patch
2. adds updated patch which addressed issues with the previous PR.
The new patch addressed the following:
- Placed `pci_reset_ongoing` variable into `pcie_service_card` (`card->pci_reset_ongoing`) instead of `mwifiex_adapter` (`adapter->pci_reset_ongoing`) (https://github.com/linux-surface/kernel/pull/57#discussion_r495454923)
- Added commit message for why the deadlock happens when reset failed (https://github.com/linux-surface/kernel/pull/57#issuecomment-699493455)
> (rework) mwifiex: pcie: skip cancel_work_sync() on reset failure path

- drivers/net/wireless/marvell/mwifiex/Makefile
- drivers/net/wireless/marvell/mwifiex/pcie.c
- drivers/net/wireless/marvell/mwifiex/pcie.h
- drivers/net/wireless/marvell/mwifiex/pcie_quirks.c
- drivers/net/wireless/marvell/mwifiex/pcie_quirks.h
This PR adds
1. DMI tables of Surface devices (first and second patch)
2. fw reset quirk for Surface gen4+ devices (third patch)
3. fw reset quirk for Surface 3 (fourth patch)
While here, created new files for quirks (`mwifiex/pcie_quirks.c` and `mwifiex/pcie_quirks.h`) because the changes are a little bit too big to add into `pcie.c`.
For Surface gen4+ devices, we can reset fw by putting wifi into D3cold then bring back into D0 (power-cycle).
For Surface 3, we can reset fw by calling _DSM method available in `\_SB.WSID` device (https://github.com/linux-surface/acpidumps/blob/05cba925f3a515f222acb5b3551a032ddde958fe/surface_3/dsdt.dsl#L11947-L12011).
Note that for Surface Pro 3, there is the same `WSID` device exists (https://github.com/linux-surface/acpidumps/blob/05cba925f3a515f222acb5b3 …
> mwifiex: add fw reset quirks for Surface devices

- drivers/net/wireless/marvell/mwifiex/main.c
- drivers/net/wireless/marvell/mwifiex/pcie.c
Hi, I've just opened a new branch that tries to fix mwifiex suspend issues in a more simple way.
Issues in upstream mwifiex regarding suspend:
- reportedly breaks S0ix on suspend
- sometimes breaks AP scanning after suspend
The previous patch `mwifiex_pcie: remove()/probe() card on suspend()/resume()` does remove()/probe() card on suspend()/resume(). This may be too aggressive.
The new patch `mwifiex: pcie: use shutdown_sw()/reinit_sw() on suspend()/resume()` tries to fix by instead sw-based way (simpler/milder)
At least I confirmed that AP scanning always works after suspend on SB1.
However, I can't confirm S0ix because SB1 can't achieve S0ix by other unknown issues anyway.
So, first, I want you folks to test if S0ix still works after this PR.
Thanks.
Note that this is not yet for …
> mwifiex: fix S0ix/AP-scanning after suspend by sw method instead of hw

- drivers/net/wireless/marvell/mwifiex/pcie.c
The devicve_dump may take a little bit long time and users may want to
disable the dump for daily usage.
This commit adds a new module parameter and disables device_dump by
default.
Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>
> mwifiex: pcie: add enable_device_dump module parameter

- drivers/net/wireless/marvell/mwifiex/sta_cmd.c
This reverts commit ef0b1af221ff57f698a303f7e332951a0052fbc3.
Reason for revert:
It seems that auto_ds won't affect stability. Let's re-enable auto_ds
and see what happens.
Signed-off-by: Tsuchiya Yuto <kitakar@gmail.com>
> Revert "mwifiex: sta_cmd: do not enable auto_ds by default"

- drivers/net/wireless/marvell/mwifiex/cfg80211.c
- drivers/net/wireless/marvell/mwifiex/pcie.c
- drivers/net/wireless/marvell/mwifiex/pcie_quirks.c
- drivers/net/wireless/marvell/mwifiex/pcie_quirks.h
- drivers/net/wireless/marvell/mwifiex/sta_cmd.c
Hi, I slightly cleaned up mwifiex patches.
1. revert some existing patches to improve changes and commit messages
2. added improved patches
`mwifiex: pcie: disable bridge_d3 for Surface gen4+`
Changes from the previous patch:
- Use recently added quirk implementation and apply for only Surface gen4+ devices
- Moved to the bottom of probe() so that quirk implementation can init before use
`mwifiex: add allow_ps_mode module parameter`
Changes from the previous patch:
- Use `-EPERM` instead of `-1` for return value when enabling ps_mode is disallowed by modparam
- changed `allow_ps_mode` modparam permission from `0444` to `0644` because it can be changed after probe as well
- Simplified comment in code
- Simplified print message
`mwifiex: mwifiex: print message when changing ps_mode`
Changes …
> mwifiex: rebase some patches

- drivers/hid/hid-multitouch.c
The Type Cover for Microsoft Surface devices supports a special usb
control request to disable or enable the built-in keyboard backlight.
On Windows, this request happens when putting the device into suspend or
resuming it, without it the backlight of the Type Cover will remain
enabled for some time even though the computer is suspended, which looks
weird to the user.
So add support for this special usb control request to hid-multitouch,
which is the driver that's handling the Type Cover.
The reason we have to use a pm_notifier for this instead of the usual
suspend/resume methods is that those won't get called in case the usb
device is already autosuspended.
Also, if the device is autosuspended, we have to briefly autoresume it
in order to send the request. Doing that should be fine, the …
> hid/multitouch: Turn off Type Cover keyboard backlight when suspending

- drivers/media/i2c/ov5693.c
- drivers/media/i2c/ov5693.h
Add V4L2_CID_HFLIP and V4L2_CID_VFLIP to support flipping the image on the sensor side.
I added some simple test cases to the ipu3 pipeline in libcamera and the image does change direction (tested on SB2). A full implementation for the ipu3 pipeline will follow later.
> ov5693: Add user controls to flip image

- drivers/media/pci/intel/ipu3/cio2-bridge.c
- drivers/media/pci/intel/ipu3/cio2-bridge.h
Expose the V4L2_CID_CAMERA_ORIENTATION and V4L2_CID_CAMERA_SENSOR_ROTATION controls to libcamera.
Currently, the values are hard-coded but we could extract them from the SSDB buffer.
> ov5693: Expose sensor orientation and rotation

- drivers/media/i2c/ov5693.c
- drivers/media/pci/intel/ipu3/cio2-bridge.c
- drivers/media/pci/intel/ipu3/cio2-bridge.h
This PR adds rotation/orientation support for cio2-bridge and ov5693.
The cio2-bridge parses the sensor orientation and rotation from the ACPI buffers and expose them as fwnodes. The ov5693 reads the values from the fwnodes and create the controls. Then libcamera picks up the controls and rotate the image in the pipeline. 
To test the whole thing you need this PR and you have to apply this [patch](https://patchwork.libcamera.org/patch/10957/) to libcamera.
Does anyone have a better idea for [this part](https://github.com/fabwu/linux-surface-kernel/commit/3c644c43e4860cacec1d8523728f3373a9fbc5fb#diff-99ed78a9282d84363094cde07371167771226cd506695acab79c3f42044db146R76-R94)? Converting the values like that feels a bit ugly...
> ipu3: Image rotation support

- drivers/misc/ipts/context.h
- drivers/misc/ipts/control.c
- drivers/misc/ipts/control.h
- drivers/misc/ipts/mei.c
- drivers/misc/ipts/protocol.h
- drivers/misc/ipts/receiver.c
- drivers/misc/ipts/receiver.h
- drivers/misc/ipts/resources.c
- drivers/misc/ipts/resources.h
- drivers/misc/ipts/uapi.c
- drivers/misc/ipts/uapi.h
- drivers/misc/mei/init.c
These changes have been sitting in the module repo for a while now, and nobody has screamed at me yet, so lets sync them into the patches.
This has a bit of everything:
- You can now reset the sensor from userspace, the master branch of iptsd already has support for this
- It doesnt require patches to the MEI bus anymore, so at least on gen4 - gen6 IPTS will work as a DKMS module. Gen7 will need upstreaming of the device ID's
- A lot of formatting stuff for eventual upstreaming (not that I want to work on that now, but it doesnt hurt).
> Sync with IPTS module repo

- drivers/media/i2c/ov5693.c
- drivers/media/i2c/ov5693.h
Hello
Here's a long batch of updates to the ov5693 driver. It's mostly tidying, with some functional changes:
- pm_runtime support replacing the existing power functions
- Fixed control setting (which previously was broken)
- Added vblank control (needed in latest versions of libcamera)
I'm planning on working on this quite a lot (meaning there'll be more to come), but I think @fabwu at least was too, so wanted to update you with what I'd done so far so we're not duplicating effort, and also because without the vblank control the driver won't work for anyone using latest versions of libcamera (already the cause of comments on #91)
Note that with later versions of libcamera this will now seem broken, when you stream in qcam it'll insta-max exposure which means the image will be white and …
> Updates and Improvements to ov5693

- drivers/misc/ipts/control.c
- drivers/misc/ipts/control.h
- drivers/misc/ipts/mei.c
- drivers/misc/ipts/protocol.h
- drivers/misc/ipts/receiver.c
- drivers/misc/ipts/uapi.c
- drivers/misc/mei/init.c
With the last set of changes to ipts I introduced a bug that only seems to surface on some devices. If the buffer addresses are not cleared during suspend, the IPTS device will not restart after resuming, because it presumably tries to write to invalid buffers now. The only way to solve this is to send `CLEAR_MEM_WINDOW` during shutdown, which means we have to readd the MEI bus patch that I tried to get rid of.
Another change is that the module will now send feedback for every buffer during shutdown. The reason for this is that `CLEAR_MEM_WINDOW` will fail with a timeout error if there is still unprocessed data around, which triggers the bug described above.
The third big change is that this includes the code to enable multitouch mode on gen7 devices. Because its only tested on a SP7 so …
> [5.11] Update IPTS based on module

- drivers/net/wireless/marvell/mwifiex/pcie.c
- drivers/net/wireless/marvell/mwifiex/pcie_quirks.c
- drivers/net/wireless/marvell/mwifiex/pcie_quirks.h
The most recent firmware of the 88W8897 card reports a hardcoded LTR
value to the system during initialization, probably as an (unsuccessful)
attempt of the developers to fix firmware crashes. This LTR value
prevents most of the Microsoft Surface devices from entering deep
powersaving states (either platform C-State 10 or S0ix state), because
the exit latency of that state would be higher than what the card can
tolerate.
Turns out the card works just the same (including the firmware crashes)
no matter if that hardcoded LTR value is reported or not, so it's kind
of useless and only prevents us from saving power.
To get rid of those hardcoded LTR reports, it's possible to reset the
PCI bridge device after initializing the cards firmware. I'm not exactly
sure why that works, maybe the power …
> mwifiex: Add quirk resetting the PCI bridge on MS Surface devices

- drivers/bluetooth/btusb.c
The Marvell 88W8897 combined wifi and bluetooth card (pcie+usb version)
is used in a lot of Microsoft Surface devices, and all those devices
suffer from very low 2.4GHz wifi connection speeds while bluetooth is
enabled. The reason for that is that the default passive scanning
interval for Bluetooth Low Energy devices is quite high in Linux
(interval of 60 msec and scan window of 30 msec, see hci_core.c), and
the Marvell chip is known for its bad bt+wifi coexisting performance.
So decrease that passive scan interval and make the scan window shorter
on this particular device to allow for spending more time transmitting
wifi signals: The new scan interval is 250 msec (0x190 * 0.625 msec) and
the new scan window is 6.25 msec (0xa * 0,625 msec).
This change has a very large impact on the …
> Bluetooth: btusb: Lower passive lescan interval on Marvell 88W8897

- drivers/net/wireless/marvell/mwifiex/cfg80211.c
Make wifi p2p actually work and fix a firmware crash when switching from station mode to AP mode.
> mwifiex: Fixes for wifi p2p and AP mode

- drivers/net/wireless/marvell/mwifiex/main.c
- drivers/net/wireless/marvell/mwifiex/pcie.c
Put the wifi card into the host sleep mode again while the device is suspended. Now that the firmware crashes are fixed, this should no longer prevent the device from waking up.
This needs more testing on other devices, but on my Surface Pro 5 (2017) I have this patch applied since last November and since then the device has never failed to wake up from suspend.
Depends on https://github.com/linux-surface/kernel/pull/70
> Reenable host sleep

- drivers/net/wireless/marvell/mwifiex/cfg80211.c
- drivers/net/wireless/marvell/mwifiex/pcie.c
- drivers/net/wireless/marvell/mwifiex/sta_cmd.c
The wifi firmware crashes are now fixed, so let's try reenabling wifi powersaving again, it's really important for power consumption and we should really try keeping it enabled.
Since @kitakar5525 mentioned in https://github.com/linux-surface/kernel/pull/70#issuecomment-726087363 that this causes connection issues on the SB1 and S3, I'd prefer if we could test this MR at least on one of those two devices before merging.
> Enable wifi powersaving by default again

- drivers/net/wireless/marvell/mwifiex/pcie.c
It seems that the firmware of the 88W8897 card sometimes ignores or
misses when we try to wake it up by reading the firmware status
register. This leads to the firmware wakeup timeout expiring and the
driver resetting the card because we assume the firmware has hung up or
crashed (unfortunately that's not unlikely with this card).
Turns out that most of the time the firmware actually didn't hang up,
but simply "missed" our wakeup request and doesn't send us an AWAKE
event.
Trying again to read the firmware status register after a short timeout
usually makes the firmware wake we up as expected, so add a small retry
loop to mwifiex_pm_wakeup_card() that looks at the interrupt status to
check whether the card woke up.
The number of tries and timeout lengths for this were determined …
> mwifiex: Try waking the firmware until we get an interrupt

- drivers/net/wireless/marvell/mwifiex/cmdevt.c
- drivers/net/wireless/marvell/mwifiex/main.c
- drivers/net/wireless/marvell/mwifiex/main.h
- drivers/net/wireless/marvell/mwifiex/sta_cmd.c
- drivers/net/wireless/marvell/mwifiex/sta_cmdresp.c
The 88W8897 pcie card with the hardware revision 20 apparently has a
hardware issue where the card wakes up from deep sleep randomly and very
often, somewhat depending on the card activity, maybe the hardware has a
floating wakeup pin or something.
Those continuous wakeups prevent the card from entering host sleep when
the computer suspends. And because the host won't answer to events from
the card anymore while it's suspended, the firmwares internal
powersaving state machine seems to get confused and the card can't sleep
anymore at all after that.
Since we can't work around that hardware bug in the firmware, let's
get the hardware revision string from the firmware and match it with
known bad revisions. Then disable auto deep sleep for those revisions,
which makes sure we no longer get …
> mwifiex: Fix host sleep without powersaving and add quirk to disable deep sleep with bad hw revisions

- drivers/net/wireless/marvell/mwifiex/sta_event.c
The firmware of the pcie 88W8897 chip sends those events very
unreliably, which means we sometimes end up actually capping the window
size while bluetooth is disabled, artifically limiting wifi speeds even
though it's not needed.
Since we can't fix the firmware, let's just ignore those events, it
seems that the Windows driver also doesn't change the rx/tx block ack
buffer sizes when bluetooth gets enabled or disabled, so this is
consistent with the Windows driver.
> mwifiex: Ignore BTCOEX events from the firmware

- drivers/media/pci/intel/ipu3/cio2-bridge.h
Orientation adds another entry to dev_properties. Increase array size accordingly.
> cio2-bridge: Use correct dev_properties size

- arch/x86/kernel/i8259.c
- drivers/acpi/acpi_apd.c
- drivers/pinctrl/pinctrl-amd.c
- drivers/tty/serial/8250/8250_dw.c
Add device IDs required for GPIO controller and UART on the SL4, as well as one fix/workaround required for its legacy PIC.
> Fixes and improved support for AMD version of Surface Laptop 4

- arch/x86/kernel/acpi/boot.c
- arch/x86/kernel/i8259.c
From the mailing list [thread](https://lore.kernel.org/lkml/20210512210459.1983026-1-luzmaximilian@gmail.com/) it sounds like using a quirk to provide an override to the irq 7 interrupt for setup of the IOAPIC is a cleaner hack for the short term.
The two commits here revert the legacy PIC workaround, and copies Thomas Gleixner's debugging patch as a temporary solution.
> Override irq7 for SL4A over probing Legacy PIC

- drivers/platform/x86/amd-pmc.c
The Surface Laptop 4 appears to have used AMD0005 for the PMC instead of
the AMDI0005 which would match the ACPI ID Registry.
AMD appears to have previously used "AMD" in a number of IDs in the past,
and AMD is not allocated to any other entity as an ID, so adding this ID
should not cause any harm.
Signed-off-by: Sachi King <nakato@nakato.io>
> platform/x86: amd-pmc: Add device HID for AMD PMC

- drivers/pinctrl/pinctrl-amd.c
- drivers/pinctrl/pinctrl-amd.h
These patches are staged for inclusion in upstream, and they are required
for interrupts that are generated from GPIO pins to be triggered, such
as the Surface Laptop 4's LID switch.
This should also hold true for the Surface Laptop 3's lid.
I pulled these patches from the patch series at:
https://patchwork.ozlabs.org/project/linux-gpio/cover/20210831120613.1514899-1-Basavaraj.Natikar@amd.com/
Ref:
AMD CPU: Waking from suspend doesn't work without external keyboard
https://github.com/linux-surface/linux-surface/issues/80
[SL4A] S0ix support on Surface Laptop 4 AMD
https://github.com/linux-surface/linux-surface/issues/458
> Amd pinctrl wakeup

- drivers/acpi/x86/s2idle.c
The Surface Laptop 4 AMD has used the AMD0005 to identify this
controller instead of using the appropriate ACPI ID AMDI0005.  The
AMD0005 needs the same special casing as AMDI0005.
> ACPI: PM: Include alternate AMDI0005 id in special behaviour

- drivers/pinctrl/pinctrl-amd.c
Some systems such as the Microsoft Surface Laptop 4 leave interrupts
enabled and configured for use in sleep states on boot, which cause
unexpected behaviour such as spurious wakes and failed resumes in
s2idle states.
As interrupts should not be enabled until they are claimed and
explicitly enabled, disabling any interrupts mistakenly left enabled by
firmware should be safe.
I've proposed this upstream at: 
https://lore.kernel.org/linux-gpio/20211001161714.2053597-1-nakato@nakato.io/T/#t
> pinctrl: amd: disable and mask interrupts on probe

- drivers/input/misc/soc_button_array.c
- drivers/platform/surface/surfacepro3_button.c
The power button on the AMD variant of the Surface Laptop uses the
same MSHW0040 device ID as the 5th and later generation of Surface
devices, however they report 0 for their OEM platform revision.  As the
AMD variant's do not need any special casing, skip calling the _DSM and
continue loading the soc_button_array.
While only the power button is used in these laptops, the volume keys
are still defined in the ACPI table.
> Input: soc_button_array - support AMD variant Surface devices

- drivers/platform/surface/surface_aggregator_registry.c
- drivers/power/supply/surface_battery.c
This moves the SSAM client devices attached to the Surface Book 3 base from the base hub to the KIP hub which seems to be the intended subsystem for managing those devices. With this change, the base hub becomes unused and can be removed.
> Move Surface Aggregator client devices on Surface Book 3 from base hub to KIP hub

- drivers/media/i2c/ov8865.c
Thanks to @jhautbois for spotting these. 
The black image problem people are having comes when the exposure set goes too close to the VTS. Most sensor drivers have some margin built in to prevent that, but I forgot to include that in the changes to the exposure control in ov8865. Add one in to avoid the black screen issue.
Opportunistically fix the max analogue gain. The field is 12 bits wide which is where the 8191 figure came from, but the driver specifies it as having a max of 16x gain
> Fixes for the ov8865 driver

- drivers/mfd/intel-lpss-pci.c
- drivers/mfd/intel-lpss.c
- drivers/mfd/intel-lpss.h
A patch from @jwrdegoede to fix the need to use the acpi_enforce_resources=lax boot param on the Go and Go2 - thanks Hans!
> mfd: intel-lpss: Fix I2C4 not being available on the Microsoft Surface Go & Go 2

- drivers/platform/x86/intel/int3472/tps68470_board_data.c
The Surface Go 3 needs some board data in order to configure the
TPS68470 PMIC - add entries to the tables in tps68470_board_data.c
that define the configuration that's needed.
Signed-off-by: Daniel Scally <djrscally@gmail.com>
> platform/x86: int3472: Add board data for Surface Go 3

- drivers/iommu/intel/iommu.c
This fixes linux-surface/intel-precise-touch/issues/3                                                                                                                               
I found a [discussion of a similar bug on launchpad](https://bugs.launchpad.net/bugs/1958004). The [suggested patch](https://launchpadlibrarian.net/586396847/43255ca.diff) is quite simple, so I have created a second patch that does the same for IPTS.
Touch and pen input now work with `intel_iommu=on` on my SB2
> Fix IOMMU errors with IPTS

- Documentation/userspace-api/media/mediactl/media-controller-model.rst
- Documentation/userspace-api/media/mediactl/media-types.rst
- drivers/media/mc/mc-entity.c
- drivers/media/v4l2-core/v4l2-async.c
- include/media/media-entity.h
- include/uapi/linux/media.h
Ancillary links are a new kind of media link intended to describe the connection between media subdevs that are intended to operate as a single logical unit, principally flash LEDs and lens motors. Libcamera supports them already and includes auto focus algorithms now (at least on master) so with this series, the world facing camera should focus properly.
> Add ancillary links

- drivers/media/pci/intel/ipu3/ipu3-cio2-main.c
@qzed: Getting the VCM to defer probe is turning out to be quite annoying. In the interim, I finally got round to this. If the VCM defers then the focus won't work, but at least everything else still should.
> media: ipu3-cio2: Move functionality from .complete() to .bound()

- drivers/hid/hid-multitouch.c
The Surface Pro Type Cover has several non standard HID usages in it's
hid report descriptor.
I noticed that, upon folding the typecover back, a vendor specific range
of 4 32 bit integer hid usages is transmitted.
Only the first byte of the message seems to convey reliable information
about the keyboard state.
0x22 => Normal (keys enabled)
0x33 => Folded back (keys disabled)
0x53 => Rotated left/right side up (keys disabled)
0x13 => Cover closed (keys disabled)
0x43 => Folded back and Tablet upside down (keys disabled)
This list may not be exhaustive.
The tablet mode switch will be disabled for a value of 0x22 and enabled
on any other value.
> hid/multitouch: Add support for surface pro type cover tablet switch

- drivers/platform/x86/intel/hid.c
The Surface Go reports Chassis Type 9 (Laptop,) so the device needs to be
added to dmi_vgbs_allow_list to enable tablet mode when an attached Type
Cover is folded back.
Relevant bug report and discussion:
https://github.com/linux-surface/linux-surface/issues/837
Signed-off-by: Duke Lee <krnhotwings@gmail.com>
> platform/x86/intel: hid: Add Surface Go to VGBS allow list

- drivers/media/pci/intel/ipu3/ipu3-cio2-main.c
This should fix the always-broken VCMs and allow cameras to work again everywhere. The VCM itself may still not work - it will depend on probe ordering, I still need to fix the missing propagation for the -EPROBE_DEFER call in the cio2-bridge. 
Sorry this took so long - I thought it was broken in some way as I couldn't get the focus to work but after extensive debugging it turned out I was just being an utter moron :D
> media: ipu3-cio2: Re-add .complete() to ipu3-cio2

- drivers/iommu/arm/arm-smmu/arm-smmu-qcom.c
We need to inform the SMMU driver of our ACPI for booting in ACPI mode to work on Windows Dev Kit 2023
> add wdk2023 acpi to smmu platlist

- drivers/platform/x86/intel/int3472/tps68470_board_data.c
Add the INT347E GPIO lookup table to the board data for the Surface Go 3. This is necessary to allow the ov7251 IR camera to probe properly on that platform.
Fixes https://github.com/linux-surface/linux-surface/issues/1055
> platform/x86: int3472: Add GPIOs to Surface Go 3 Board data

- drivers/platform/x86/intel/int3472/discrete.c
ACPI _HID INT347E represents the OmniVision 7251 camera sensor. The driver for this sensor expects a single pin named "enable", but on some Microsoft Surface platforms the sensor is assigned a single GPIO who's type flag is INT3472_GPIO_TYPE_RESET.
Remap the GPIO pin's function from "reset" to "enable". This is done outside of the existing remap table since it is a more widespread discrepancy than that method is designed for. Additionally swap the polarity of the pin to match the driver's expectation.
> platform/x86: int3472: Remap reset GPIO for INT347E

- drivers/hid/ipts/hid.c
- drivers/hid/ipts/receiver.c
- drivers/hid/ipts/resources.c
- drivers/hid/ipts/resources.h
Changes:
* Fix redefinition error on AOSP clang
* Increase the polling frequency to reduce latency
* Don't allocate a new buffer for every HID report
* Always use the generic HID driver instead of forcing hid-multitouch
Based on https://github.com/linux-surface/intel-precise-touch/commit/a2b675d72dbde80ebe36a5b6ceaebd596c030314
> Update IPTS from module repo

- drivers/media/v4l2-core/v4l2-subdev.c
Hey - here's the proper fix for the camera pagefault. We probably also want to fix the IPU3 driver since it never really should have used v4l2_subdev_link_validate(), but that's a separate thing.
> Correct fix for memory pagefault when using cameras

- Documentation/hwmon/index.rst
- Documentation/hwmon/surface_fan.rst
- MAINTAINERS
- drivers/hwmon/Kconfig
- drivers/hwmon/Makefile
- drivers/hwmon/surface_fan.c
- drivers/platform/surface/surface_aggregator_registry.c
This pull request has quite a lengthy amount of comments with analysis, updating the description with a short recap to get people from the future up to speed:
- This module only adds fan monitoring support to the hwmon subystem.
- Fan control was not achieved, in the end, even Windows does [not control](https://github.com/linux-surface/kernel/pull/144#issuecomment-1853123261) the fan directly.
- It was identified that on Windows switching platform profiles does switch the fan profile as well, resulting in better cooling performance.
- Changes to the platform profile module are proposed in https://github.com/linux-surface/kernel/pull/145 to have similar functionality.
First of; thanks for the great work to support Linux on these devices, I wouldn't have bought a Surface had it not been for …
> Surface fan module

- drivers/media/i2c/dw9719.c
- drivers/media/pci/intel/ipu3/ipu3-cio2.c
- drivers/staging/media/ipu3/ipu3-v4l2.c
After linux-6.7(or 6.6?), ipu3-imgu and dw9719 are broken. See https://github.com/linux-surface/linux-surface/issues/1323.
This patches fix those issues.
Tested on Surface Go 2.
> Fix camera issues in 6.7.x on SGo2

- drivers/media/i2c/dw9719.c
In #146, I reverted upstream dw9719 driver to the old one.
This PR allows using upstream driver on surface go 2.
> Use upstream dw9719 driver

- drivers/platform/surface/aggregator/core.c
Failure of probing of SSAM serial hub was observed (https://github.com/linux-surface/linux-surface/issues/1271) from time to time due to race condition where the underlying uart device could be not ready at the point calling serdev_device_open(). Specifically, the failing path is
```
ssam_serial_hub_probe()
=> serdev_device_open()
=> ctrl->ops->open() // this is ttyport_open()
=> tty->ops->open() // this is uart_open()
=> tty_port_open()
=> port->ops->activate() // this is uart_port_activate()
Find bit UPF_DEAD is set in uport->flags and fail with errno -ENXIO.
```
Retrying upon failure in opening serdev device would greatly alleviate this situation.  Tested with my Surface Pro 5 rebooting for 10+ times and didn't see the issue anymore.
I admit this solution might be suboptimal, but it …
> platform/surface: aggregator: Defer probing when serdev is not ready

- drivers/hwmon/surface_fan.c
Compiling with CONFIG_WERROR enabled fails because of -Wmissing-prototypes.
> Make surface_fan_hwmon_is_visible static to avoid compiler warning.

- Documentation/admin-guide/kernel-parameters.txt
- kernel/power/hibernate.c
Expose an optional lockdown_hibernate kernel parameter to enable hibernation during kernel lockdown mode. The patch was imported from [here](https://gist.github.com/brknkfr/95d1925ccdbb7a2d18947c168dfabbee).
Closes https://github.com/linux-surface/linux-surface/issues/1543
> Added patch to allow optional hibernate during lockdown
